from .caja import Caja
from .categoria import Categoria
from .cliente import Cliente
from .detallePromocion import DetallePromocion
from .detalleVenta import DetalleVenta
from .empleado import Empleado
from .pago import Pago
from .producto import Producto
from .promocion import Promocion
from .proveedor import Proveedor
from .receta import Receta
from .rol import Rol
from .tipoPago import TipoPago
from .usuario import Usuario
from .venta import Venta