# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menuInicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_POS(object):
    def setupUi(self, POS):
        POS.setObjectName("POS")
        POS.setEnabled(True)
        POS.resize(1138, 632)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../.designer/backup/logoPasteleria.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        POS.setWindowIcon(icon)
        self.widget_2 = QtWidgets.QWidget(POS)
        self.widget_2.setGeometry(QtCore.QRect(-20, 0, 1161, 631))
        self.widget_2.setStyleSheet("background-color: #CFC3F5;")
        self.widget_2.setObjectName("widget_2")
        self.contrasteWidget = QtWidgets.QWidget(self.widget_2)
        self.contrasteWidget.setGeometry(QtCore.QRect(0, 0, 1161, 61))
        self.contrasteWidget.setAutoFillBackground(False)
        self.contrasteWidget.setStyleSheet("background-color: #867BAA")
        self.contrasteWidget.setObjectName("contrasteWidget")
        self.tituloLabel = QtWidgets.QLabel(self.contrasteWidget)
        self.tituloLabel.setGeometry(QtCore.QRect(110, 10, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Serif Display SemiCondensed Black")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tituloLabel.setFont(font)
        self.tituloLabel.setStyleSheet("color: rgb(0, 0, 0);")
        self.tituloLabel.setObjectName("tituloLabel")
        self.label_2 = QtWidgets.QLabel(self.contrasteWidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 51, 41))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Iconos/logoPasteleriaMini.xcf"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.widgetSidebar = QtWidgets.QWidget(self.widget_2)
        self.widgetSidebar.setGeometry(QtCore.QRect(10, 60, 60, 471))
        self.widgetSidebar.setStyleSheet("background-color: #988DBD;\n"
"border: none;")
        self.widgetSidebar.setObjectName("widgetSidebar")
        self.btnToggle = QtWidgets.QPushButton(self.widgetSidebar)
        self.btnToggle.setGeometry(QtCore.QRect(10, 10, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnToggle.setFont(font)
        self.btnToggle.setStyleSheet("QPushButton {\n"
"    background-color: #867BAA;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #4a6378;\n"
"}")
        self.btnToggle.setObjectName("btnToggle")
        self.pushButton_2 = QtWidgets.QPushButton(self.widgetSidebar)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 80, 81, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widgetSidebar)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 120, 81, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widgetSidebar)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 260, 81, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(70, 60, 1091, 571))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameLeft = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frameLeft.setEnabled(True)
        self.frameLeft.setMinimumSize(QtCore.QSize(400, 0))
        self.frameLeft.setStyleSheet("background-color: rgb(189, 177, 226);\n"
"border-right: 2px solid #867BAA;")
        self.frameLeft.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLeft.setObjectName("frameLeft")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frameLeft)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 631, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_left = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_left.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_left.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_left.setSpacing(10)
        self.verticalLayout_left.setObjectName("verticalLayout_left")
        self.horizontalLayout_search = QtWidgets.QHBoxLayout()
        self.horizontalLayout_search.setSpacing(10)
        self.horizontalLayout_search.setObjectName("horizontalLayout_search")
        self.searchInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.searchInput.setMinimumSize(QtCore.QSize(40, 0))
        self.searchInput.setStyleSheet("QLineEdit {\n"
"    padding: 10px;\n"
"    border: 2px solid #bdc3c7;\n"
"    border-radius: 20px;\n"
"    font-size: 14px;\n"
"}")
        self.searchInput.setObjectName("searchInput")
        self.horizontalLayout_search.addWidget(self.searchInput)
        self.categoryCombo = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.categoryCombo.setMinimumSize(QtCore.QSize(150, 0))
        self.categoryCombo.setStyleSheet("QComboBox {\n"
"    padding: 10px;\n"
"    border: 3px solid #bdc3c7;\n"
"    border-radius: 20px;\n"
"}\n"
"")
        self.categoryCombo.setObjectName("categoryCombo")
        self.horizontalLayout_search.addWidget(self.categoryCombo)
        self.verticalLayout_left.addLayout(self.horizontalLayout_search)
        self.productsScrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.productsScrollArea.setAutoFillBackground(True)
        self.productsScrollArea.setStyleSheet("QScrollArea { border: none; }")
        self.productsScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.productsScrollArea.setWidgetResizable(True)
        self.productsScrollArea.setObjectName("productsScrollArea")
        self.scrollContentWidget = QtWidgets.QWidget()
        self.scrollContentWidget.setGeometry(QtCore.QRect(0, 0, 611, 456))
        self.scrollContentWidget.setObjectName("scrollContentWidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollContentWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 611, 451))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.productsGridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.productsGridLayout.setContentsMargins(0, 0, 0, 0)
        self.productsGridLayout.setSpacing(15)
        self.productsGridLayout.setObjectName("productsGridLayout")
        self.productsScrollArea.setWidget(self.scrollContentWidget)
        self.verticalLayout_left.addWidget(self.productsScrollArea)
        self.horizontalLayout.addWidget(self.frameLeft)
        self.frameRigth = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frameRigth.setMinimumSize(QtCore.QSize(300, 0))
        self.frameRigth.setStyleSheet("styleSheet**: background-color: white;")
        self.frameRigth.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameRigth.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRigth.setObjectName("frameRigth")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frameRigth)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 421, 551))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayoutRight = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayoutRight.setContentsMargins(10, 10, 10, 10)
        self.verticalLayoutRight.setSpacing(10)
        self.verticalLayoutRight.setObjectName("verticalLayoutRight")
        self.saleTitleLabel = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.saleTitleLabel.setStyleSheet("QLabel {\n"
"    color: #000000;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    padding: 10px;\n"
"    background-color: #867BAA;\n"
"    border-radius: 5px;\n"
"    border: 1px solid #bdc3c7;\n"
"}")
        self.saleTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.saleTitleLabel.setObjectName("saleTitleLabel")
        self.verticalLayoutRight.addWidget(self.saleTitleLabel)
        self.salesTable = QtWidgets.QTableWidget(self.verticalLayoutWidget_3)
        self.salesTable.setStyleSheet("QTableWidget {\n"
"    border: 1px solid #bdc3c7;\n"
"    border-radius: 5px;\n"
"    background-color: white;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #867BAA;\n"
"    color: white;\n"
"    padding: 8px;\n"
"    border: none;\n"
"    font-weight: bold;\n"
"}")
        self.salesTable.setAlternatingRowColors(True)
        self.salesTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.salesTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.salesTable.setColumnCount(3)
        self.salesTable.setObjectName("salesTable")
        self.salesTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.salesTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.salesTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.salesTable.setHorizontalHeaderItem(2, item)
        self.salesTable.horizontalHeader().setCascadingSectionResizes(False)
        self.salesTable.horizontalHeader().setSortIndicatorShown(False)
        self.salesTable.horizontalHeader().setStretchLastSection(False)
        self.verticalLayoutRight.addWidget(self.salesTable)
        self.totalsFrame = QtWidgets.QFrame(self.verticalLayoutWidget_3)
        self.totalsFrame.setStyleSheet("QFrame {\n"
"    background-color: #CFC3F5;\n"
"    border: 1px solid #bdc3c7;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"}")
        self.totalsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.totalsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.totalsFrame.setObjectName("totalsFrame")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.totalsFrame)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 401, 231))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_discount = QtWidgets.QHBoxLayout()
        self.horizontalLayout_discount.setObjectName("horizontalLayout_discount")
        self.subtotalLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.subtotalLabel.setStyleSheet("color: #7f8c8d; font-size: 14px;")
        self.subtotalLabel.setObjectName("subtotalLabel")
        self.horizontalLayout_discount.addWidget(self.subtotalLabel)
        self.discountPercent = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.discountPercent.setEnabled(False)
        self.discountPercent.setDecimals(1)
        self.discountPercent.setMaximum(50.0)
        self.discountPercent.setProperty("value", 10.0)
        self.discountPercent.setObjectName("discountPercent")
        self.horizontalLayout_discount.addWidget(self.discountPercent)
        self.discountCheckbox = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.discountCheckbox.setStyleSheet("gridline-color: rgb(0, 0, 0);")
        self.discountCheckbox.setChecked(False)
        self.discountCheckbox.setObjectName("discountCheckbox")
        self.horizontalLayout_discount.addWidget(self.discountCheckbox)
        self.gridLayout.addLayout(self.horizontalLayout_discount, 1, 0, 1, 1)
        self.discountAmountLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.discountAmountLabel.setStyleSheet("color: #e74c3c; font-size: 14px;")
        self.discountAmountLabel.setObjectName("discountAmountLabel")
        self.gridLayout.addWidget(self.discountAmountLabel, 2, 0, 1, 1)
        self.totalLabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.totalLabel.setStyleSheet("color: #c0392b; font-size: 18px; font-weight: bold;")
        self.totalLabel.setObjectName("totalLabel")
        self.gridLayout.addWidget(self.totalLabel, 5, 0, 1, 1)
        self.vhorizontalLayoutButtons = QtWidgets.QHBoxLayout()
        self.vhorizontalLayoutButtons.setSpacing(10)
        self.vhorizontalLayoutButtons.setObjectName("vhorizontalLayoutButtons")
        self.clearButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.clearButton.setStyleSheet("QPushButton {\n"
"    background-color: #e74c3c;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #c0392b;\n"
"}")
        self.clearButton.setObjectName("clearButton")
        self.vhorizontalLayoutButtons.addWidget(self.clearButton)
        self.payButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.payButton.setStyleSheet("QPushButton {\n"
"    background-color: #27ae60;\n"
"    color: white;\n"
"    padding: 10px;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #229954;\n"
"}")
        self.payButton.setObjectName("payButton")
        self.vhorizontalLayoutButtons.addWidget(self.payButton)
        self.gridLayout.addLayout(self.vhorizontalLayoutButtons, 4, 0, 1, 1)
        self.paymentCombo = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.paymentCombo.setStyleSheet("background-color: rgb(189, 177, 226);\n"
"border-left-color: rgb(0, 0, 0);")
        self.paymentCombo.setObjectName("paymentCombo")
        self.paymentCombo.addItem("")
        self.paymentCombo.addItem("")
        self.paymentCombo.addItem("")
        self.gridLayout.addWidget(self.paymentCombo, 3, 0, 1, 1)
        self.verticalLayoutRight.addWidget(self.totalsFrame)
        self.verticalLayoutRight.setStretch(1, 4)
        self.verticalLayoutRight.setStretch(2, 4)
        self.salesTable.raise_()
        self.saleTitleLabel.raise_()
        self.totalsFrame.raise_()
        self.horizontalLayout.addWidget(self.frameRigth)
        self.horizontalLayout.setStretch(0, 6)
        self.horizontalLayout.setStretch(1, 4)

        self.retranslateUi(POS)
        QtCore.QMetaObject.connectSlotsByName(POS)

    def retranslateUi(self, POS):
        _translate = QtCore.QCoreApplication.translate
        POS.setWindowTitle(_translate("POS", "AlquimiaPastelería"))
        self.tituloLabel.setText(_translate("POS", "Alquimia Pastelería"))
        self.btnToggle.setText(_translate("POS", "☰"))
        self.pushButton_2.setText(_translate("POS", "PushButton"))
        self.pushButton_3.setText(_translate("POS", "PushButton"))
        self.pushButton_4.setText(_translate("POS", "PushButton"))
        self.searchInput.setPlaceholderText(_translate("POS", "Buscar productos..."))
        self.saleTitleLabel.setText(_translate("POS", "Resumen de Venta"))
        item = self.salesTable.horizontalHeaderItem(0)
        item.setText(_translate("POS", "Producto"))
        item = self.salesTable.horizontalHeaderItem(1)
        item.setText(_translate("POS", "Cantidad"))
        item = self.salesTable.horizontalHeaderItem(2)
        item.setText(_translate("POS", "SubTotal"))
        self.subtotalLabel.setText(_translate("POS", "Subtotal: $0.00"))
        self.discountPercent.setSuffix(_translate("POS", "%"))
        self.discountCheckbox.setText(_translate("POS", "Aplicar Descuento"))
        self.discountAmountLabel.setText(_translate("POS", "Descuento: $0.00"))
        self.totalLabel.setText(_translate("POS", "TOTAL: $0.00"))
        self.clearButton.setText(_translate("POS", "Limpiar Venta"))
        self.payButton.setText(_translate("POS", "Realizar Pago"))
        self.paymentCombo.setItemText(0, _translate("POS", "Efectivo"))
        self.paymentCombo.setItemText(1, _translate("POS", "Tarjeta"))
        self.paymentCombo.setItemText(2, _translate("POS", "Transferencia"))
