from .productoController import ProductoController
from .rolController import RolController
from .empleadoController import EmpleadoController
from .usuarioController import UsuarioController
from .categoriaController import CategoriaController
from .proveedorController import ProveedorController
from .clienteController import ClienteController
from .recetaController import RecetaController
from .promocionController import PromocionController
